### ISSUE TITLE
在mac上，make失败

### ISSUE THREAD

**Issue by luckypoem** [csujedihy/jedisocks#7]
hi.

yudeMacBook-Air:build brite$ ls
CMakeCache.txt      Makefile        cmake_install.cmake
CMakeFiles      bin
yudeMacBook-Air:build brite$ make
Scanning dependencies of target js-local
[  8%] Building C object bin/CMakeFiles/js-local.dir/local.c.o
/Users/brite/jedisocks/src/local.c:5:10: fatal error: 'uv.h' file not found
# include <uv.h>

```
     ^
```

1 error generated.
make[2]: **\* [bin/CMakeFiles/js-local.dir/local.c.o] Error 1
make[1]: **\* [bin/CMakeFiles/js-local.dir/all] Error 2
make: **\* [all] Error 2
yudeMacBook-Air:build brite$

如何解决？
linux vps上，没问题。

**Comment by csujedihy** [comment]
libuv没安，步骤里面不是写的很清楚吗？

**Comment by luckypoem** [comment]
libuv装了。我昨天就装了。

yudeMacBook-Air:libuv brite$ make install
 /usr/local/bin/gmkdir -p '/usr/local/lib'
 /bin/sh ./libtool   --mode=install /usr/local/bin/ginstall -c   libuv.la '/usr/local/lib'
libtool: install: /usr/local/bin/ginstall -c .libs/libuv.1.dylib /usr/local/lib/libuv.1.dylib
libtool: install: (cd /usr/local/lib && { ln -s -f libuv.1.dylib libuv.dylib || { rm -f libuv.dylib && ln -s libuv.1.dylib libuv.dylib; }; })
libtool: install: /usr/local/bin/ginstall -c .libs/libuv.lai /usr/local/lib/libuv.la
libtool: install: /usr/local/bin/ginstall -c .libs/libuv.a /usr/local/lib/libuv.a
libtool: install: chmod 644 /usr/local/lib/libuv.a
libtool: install: ranlib /usr/local/lib/libuv.a
 /usr/local/bin/gmkdir -p '/usr/local/include'
 /usr/local/bin/ginstall -c -m 644 include/uv.h include/uv-errno.h include/uv-threadpool.h include/uv-version.h include/uv-unix.h include/uv-darwin.h include/pthread-barrier.h '/usr/local/include'
 /usr/local/bin/gmkdir -p '/usr/local/lib/pkgconfig'
 /usr/local/bin/ginstall -c -m 644 libuv.pc '/usr/local/lib/pkgconfig'
yudeMacBook-Air:libuv brite$ cd ~/jedisocks
yudeMacBook-Air:jedisocks brite$ ls
CMakeLists.txt  LICENSE     README.md   build       src
yudeMacBook-Air:jedisocks brite$ cd build
yudeMacBook-Air:build brite$ ls
CMakeCache.txt      Makefile        cmake_install.cmake
CMakeFiles      bin
yudeMacBook-Air:build brite$ make
[  8%] Building C object bin/CMakeFiles/js-local.dir/local.c.o
/Users/brite/jedisocks/src/local.c:5:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^
1 error generated.
make[2]: **\* [bin/CMakeFiles/js-local.dir/local.c.o] Error 1
make[1]: **\* [bin/CMakeFiles/js-local.dir/all] Error 2
make: **\* [all] Error 2
yudeMacBook-Air:build brite$ 

我在google上搜了一下“fatal error: 'uv.h' file not found”，没找到解决办法。

谢谢你的回复。

**Comment by luckypoem** [comment]
看了这个http://stackoverflow.com/questions/34896114/how-to-install-c-library-libuv-on-os-x ，也没搞定
